// Code generated by hertz generator.

package main

import (
	"flag"

	"hertz_test/resource"

	"github.com/cloudwego/hertz/pkg/app/server"
	"gitlab.appshahe.com/service-cloud-rec/rec-utils.git/component/log"
)

var (
	env       string
	configDir string
)

func main() {

	flag.StringVar(&env, "env", "dev", "config env name")
	flag.StringVar(&configDir, "config_dir", "./config/config_file", "config file dir")
	flag.Parse()

	if err := resource.Init(env, configDir); err != nil {
		log.Base().Error("global init: ", err)
		return
	}

	h := server.Default(server.WithHostPorts("0.0.0.0:8080"))

	register(h)
	h.Spin()
}
